global:
  # ResolveTimeout is the time after which an alert is declared resolved
  # if it has not been updated.
  resolve_timeout: 5m


  # The default SMTP From header field.
  smtp_from: no-reply@msp-pcalerts.nutanix.com

  # The default SMTP smarthost used for sending emails, including port number.
  # Port number usually is 25, or 587 for SMTP over TLS (sometimes referred to
  # as STARTTLS).
  smtp_smarthost: mailrelay.dyn.nutanix.com:25

  smtp_require_tls: false


# A list of notification receivers.
receivers:
- name: "null"

- name: email
  email_configs:
  - to: rohith.subramanyam@nutanix.com

- name: ntnx-system-webhook
  webhook_configs:
  - url: "http://am-webhook.ntnx-system/webhook"


# The root node of the routing tree.
route:
  # The labels by which incoming alerts are grouped together. For example,
  # multiple alerts coming in for cluster=A and alertname=LatencyHigh would
  # be batched into a single group.
  group_by:
  - job

  # How long to wait before sending a notification about new alerts that
  # are added to a group of alerts for which an initial notification has
  # already been sent.
  group_interval: 5m

  # How long to initially wait to send a notification for a group
  # of alerts. Allows to wait for an inhibiting alert to arrive or collect
  # more initial alerts for the same group.
  group_wait: 30s

  receiver: ntnx-system-webhook

  # How long to wait before sending a notification again if it has already
  # been sent successfully for an alert.
  repeat_interval: 12h

  # Child routes.
  routes:
  # A set of equality matchers an alert has to fulfill to match the node.
  - match:
      alertname: DeadMansSwitch
    receiver: "null"