apiVersion: apps/v1
kind: Deployment
metadata:
  name: am-webhook
  namespace: ntnx-system
  labels:
    app: am-webhook
spec:
  replicas: 2
  selector:
    matchLabels:
      app: am-webhook
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 1
  template:
    metadata:
      labels:
        app: am-webhook
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: am-webhook
        image: rohithvsm/rohithvsm:alertmgrwebhook
        imagePullPolicy: Always
        env:
          - name: PORT
            value: "80"

        #livenessProbe:
          #httpGet:
            #path: /healthz
            #port: 80
        #readinessProbe:
          #httpGet:
            #path: /healthz
            #port: 80

        resources:
          limits:
            cpu: 10m
            memory: 30Mi
          requests:
            cpu: 10m
            memory: 30Mi
