apiVersion: v1
kind: Service
metadata:
  name: am-webhook
  labels:
  name: am-webhook
  namespace: ntnx-system
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: am-webhook
